### ISSUE TITLE
HEIF format not working

### ISSUE THREAD

**Issue by jimneff440** [alexcorvi/heic2any#10]
Here is a sample file
[Link for file](https://www.aconvert.com/samples/sample.heif)

**Comment by GeorgeBelanger** [comment]
I had this issue but found out that I was creating the blob in the wrong way. I was doing a 

reader.onload = function(e) {
   const blob = new Blob([e.target.result])
   img.src = heic2any({blob})
}

when what I needed to do was 

         fetch(e.target.result)
            .then((res) => res.blob())
            .then((blob) => heic2any({
              blob
           })).then((conversionResult) => {
              var url = URL.createObjectURL(conversionResult);
              img.src = url;
            })

**Comment by alexcorvi** [comment]
Solved in the latest version.
