### ISSUE TITLE
Slant Image after converting

### ISSUE THREAD

**Issue by championboylay** [alexcorvi/heic2any#16]
Most of the heic work well . However some of heic file can convert successfully but converted image become slant.

This is converted result.
![Converted_Image](https://user-images.githubusercontent.com/2637794/105448533-e0bff300-5ca4-11eb-836b-3f37c65a0a2f.gif)

This is original image.

[Original_Image.zip](https://github.com/alexcorvi/heic2any/files/5853668/Original_Image.zip)

**Comment by KNazarenko** [comment]
Hi,

I ran into this when testing too.

Here are a few more pictures that are not being converted correctly.

![heic2jpeg](https://user-images.githubusercontent.com/32453503/112022798-4ad90500-8b3b-11eb-9953-f4891ede5ffe.jpg)

There are heic original pictures:
[original_pictures.zip](https://github.com/alexcorvi/heic2any/files/6183729/original_pictures.zip)

**Comment by delphist** [comment]
seems to be fixed just by updating `libheif` library
https://github.com/alexcorvi/heic2any/pull/27
