### ISSUE TITLE
QQ, how does this compare to ImageMagick (convert / mogrify)?

### ISSUE THREAD

**Issue by xanoni** [alexcorvi/heic2any#22]
I am aware that this runs in the browser, whereas ImageMagick doesn't. However, I'm curious how the output compares to ImageMagick ("convert" / "mogrify" on command line). Thank you.

**Comment by alexcorvi** [comment]
This runs in the browser, whereas ImageMagick doesn't. And it uses [libheif](https://github.com/strukturag/libheif).
