### ISSUE TITLE
Not working on Chrome for android

### ISSUE THREAD

**Issue by Hajzenberg** [alexcorvi/heic2any#31]
It looks like call to heic2any in Chrome for android never finishes execution. Same on iOS.

const jpegBlob = await heic2any({
      // required: the HEIF blob file
      blob: file,
      // (optional) MIME type of the target file
      // it can be "image/jpeg", "image/png" or "image/gif"
      // defaults to "image/png"
      toType: 'image/jpeg',
      // conversion quality
      // a number ranging from 0 to 1
      quality: 0.5,
    });

Did anyone manage to make it work on mobile browsers?

**Comment by FalconKul** [comment]
maybe the following guide on StackOverflow can help you:
https://stackoverflow.com/questions/64695144/angular-9-how-to-convert-heif-file-format-to-a-known-web-format-when-uploading/64695145#64695145

**Comment by mhrastegari** [comment]
Same issue! I can convert and upload heic files on Windows and iOS but not Android!
