### ISSUE TITLE
Conversion slow

### ISSUE THREAD

**Issue by uxcodev** [alexcorvi/heic2any#36]
Converting a 1.6mb HEIC image is taking about 5 seconds. Is this normal? And is there any way to speed it up?

My code:
...
const start = window.performance.now();
let image = await heic2any({ blob:file });
const stop = window.performance.now();
console.log('Elapsed time for heic2any: ${(stop - start) / 1000}s');
...

Result in console log:
`Elapsed time for heic2any: 5.121s`

For the sake of comparison, I tried converting the same image to PNG before uploading, which resulted in a 14.6mb file and it still only took 0.1 seconds for the entire upload.

**Comment by av01d** [comment]
I experience the same. It's rather slow, but it works great. I just show a spinner/throbber to the user.

**Comment by kinton** [comment]
On my android it takes about 2 minutes with 3 Mb heic file
