### ISSUE TITLE
take photo of xiaomi 10 is not  support?

### ISSUE THREAD

**Issue by xjccc** [alexcorvi/heic2any#37]
the photo type is HEIC, but heic2any is not support😭
[heic-source](https://github.com/xjccc/heic-source)

**Comment by alexcorvi** [comment]
Please make sure that the file you're passing is actually a HEIC image, some devices convert images to JPEG/GIF before passing them to a browser or transferring them. You attach the image file here so I can take a more in-depth look.

**Comment by xjccc** [comment]
> Please make sure that the file you're passing is actually a HEIC image, some devices convert images to JPEG/GIF before passing them to a browser or transferring them. You attach the image file here so I can take a more in-depth look.

[heic](https://github.com/xjccc/heic-source/blob/master/1.heic)
[heif](https://github.com/xjccc/heic-source/blob/master/2.heif)

can u download these file?

here is not support file type.

thank u

**Comment by alexcorvi** [comment]
I've tried the files that you've attached with the latest version and it's working! the latest update might have solved your issue.
Thank you

**Comment by xjccc** [comment]
> I've tried the files that you've attached with the latest version and it's working! the latest update might have solved your issue. Thank you

ok.thank u very much

**Comment by fahmilatib** [comment]
> I've tried the files that you've attached with the latest version and it's working! the latest update might have solved your issue.

@alexcorvi perhaps you forgot to release it https://github.com/alexcorvi/heic2any/releases
