### ISSUE TITLE
It seems an odd error in the converted picture after the original picture was edited in iPhone album

### ISSUE THREAD

**Issue by Simon-live** [alexcorvi/heic2any#42]
Test Device: iPhoneXR, iPhone13 Pro
<img width="1415" alt="截屏2022-09-22 10 41 31" src="https://user-images.githubusercontent.com/39435485/191715266-70c84c4e-8161-485d-aa78-4db8aacb11a3.png">
I test it via your demo, the same bug happens as my program, I don't know how to solve this.

**Comment by vppics** [comment]
I have the same problem, the result image is being distorted. Any updates on this?

**Comment by eduff0** [comment]
I have the same issue.  It has occurred during heic conversion to both png and jpg.  It doesn't seem to occur for all images that I try.

![skewed](https://user-images.githubusercontent.com/122957991/213090669-c444845f-853c-4192-98a3-0dea7d33cac5.png)

**Comment by alexcorvi** [comment]
Would you please try again after the latest update, or attach the heic image here so I can take a look

**Comment by vppics** [comment]
@alexcorvi It works fine now. Thanks a lot for the fix.
