### ISSUE TITLE
Script Freezes on production deploy

### ISSUE THREAD

**Issue by zacharytyhacz** [alexcorvi/heic2any#6]
Hello, thanks for creating this heic2any library for us.

I'm using nuxtjs, and running the `nuxt build` command to minify and prepare the project source code for a production deploy. See: https://nuxtjs.org/guide/commands#server-side-rendered-deployment-universal-ssr-

This is the minimal code I'm using at the moment:
```javascript
var heic2any = require('heic2any');
file = await heic2any({
    blob: file,
    toType: "image/jpeg",
    quality: 0.75,
});
```

In dev-mode is works fine, though once in production mode my whole browser freezes and my cpu usage goes through the roof. This happens on all browsers and can be reproduced on other people's devices as well. 
**Also, there is no errors in the console**

 ( **Mac High Sierra 10.13 - on Firefox, Chrome, and Safari**)

Also, on mobile IOS devices via Safari, it still breaks, though the image conversion breaks and the resulting output image is a broken image. See below:
![image](https://user-images.githubusercontent.com/38140593/71427733-9c20ed00-2689-11ea-8cbc-a0eae77951d3.png)

Any idea whats going on?

**Comment by leovvay** [comment]
have same thing here, it's just frozen on prod

**Comment by Pinkdonuts** [comment]
have same error too.

**Comment by domeknn** [comment]
+1

**Comment by alexcorvi** [comment]
I'm not very familiar with nuxt.js and Vue.
Please check if your issue with is solved in the 0.0.3 release, if not then a recreation of the bug in a repo would be really appreciated.

[0.0.3 release note](https://github.com/alexcorvi/heic2any/releases/tag/0.0.3)

**Comment by zacharytyhacz** [comment]
@alexcorvi  Ok, I'll put a minimal project together within the next couple days ( unless some else out there has one ) 

I haven't tried out with that latest 0.0.3 release, I will give that shot as well

thanks

**Comment by zacharytyhacz** [comment]
Hello everyone.

I attempted the same exact code and project with the latest `0.0.3` version and everything works.

I'm having trouble creating a minimal test project for `0.0.1` because for nuxt it has to built for production, not just development. 

I'm going to close this, `0.0.3` did stuff that fixed it.
